myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path

from project import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('index/', views.index),
    path('login/', views.login),
    path('login/validate', views.login_validate),
    path('register', views.register),
    path('logout', views.logout),
    path('physical_outcome_measures/', views.pom),
    path('measurement_research/', views.mr),
    path('self-reported_measures/', views.sfm),
    path('contact/', views.contact),
    path('ims/submit', views.ims_submit),
    path('ims/', views.ims),
    path('jf/submit', views.jf_submit),
    path('jf/', views.jf),
    path('fp/submit', views.fp_submit),
    path('fp/', views.fp),
    path('history/get', views.history_get),
    path('history/', views.history),
    #path('csv/', views.csv_input),
]

myproject/project/models.py
from django.db import models

# Create your models here.

gender = (
    ('male','male'),
    ('female','female'),
)

evaluation = (
    ('Weak','Weak'),
    ('Normal','Normal'),
    ('Strong','Strong'),
)

class User(models.Model):

    uid = models.AutoField(primary_key=True)
    username = models.CharField(max_length=128)
    password = models.CharField(max_length=256)
    #sex = models.CharField(max_length=32,choices=gender, default='male')
    email = models.EmailField(unique=True, default='123@123.com')
    c_time = models.DateTimeField(auto_now_add=True)
 
    def __str__(self):
        return self.email

class IMS (models.Model):

    age_group = models.IntegerField(default=0)
    sex = models.CharField(max_length=32,choices=gender, default='male')

    gs_mean = models.IntegerField(default=0)
    apfs_mean = models.IntegerField(default=0)
    ads_mean = models.IntegerField(default=0)
    kfs_mean = models.IntegerField(default=0)
    kes_mean = models.IntegerField(default=0)
    has_mean = models.IntegerField(default=0)
    hers_mean = models.IntegerField(default=0)
    hirs_mean = models.IntegerField(default=0)
    efs_mean = models.IntegerField(default=0)
    ees_mean = models.IntegerField(default=0)
    sers_mean = models.IntegerField(default=0)
    sirs_mean = models.IntegerField(default=0)

    gs_sd = models.IntegerField(default=0)
    apfs_sd = models.IntegerField(default=0)
    ads_sd = models.IntegerField(default=0)
    kfs_sd = models.IntegerField(default=0)
    kes_sd = models.IntegerField(default=0)
    has_sd = models.IntegerField(default=0)
    hers_sd = models.IntegerField(default=0)
    hirs_sd = models.IntegerField(default=0)
    efs_sd = models.IntegerField(default=0)
    ees_sd = models.IntegerField(default=0)
    sers_sd = models.IntegerField(default=0)
    sirs_sd = models.IntegerField(default=0)

    def __str__(self):
        return str(self.sex)+' '+str(self.age_group)

class History_IMS (models.Model):
    user = models.ForeignKey('User', on_delete=models.CASCADE)

    sex = models.CharField(max_length=32,choices=gender, default='male')
    age = models.IntegerField(default=0)

    gs = models.IntegerField(default=0)
    apfs = models.IntegerField(default=0)
    ads = models.IntegerField(default=0)
    kfs = models.IntegerField(default=0)
    kes = models.IntegerField(default=0)
    has = models.IntegerField(default=0)
    hers = models.IntegerField(default=0)
    hirs = models.IntegerField(default=0)
    efs = models.IntegerField(default=0)
    ees = models.IntegerField(default=0)
    sers = models.IntegerField(default=0)
    sirs = models.IntegerField(default=0)

    gs_eval = models.CharField(max_length=32,choices=evaluation, default='Weak')
    apfs_eval = models.CharField(max_length=32,choices=evaluation, default='Weak')
    ads_eval = models.CharField(max_length=32,choices=evaluation, default='Weak')
    kfs_eval = models.CharField(max_length=32,choices=evaluation, default='Weak')
    kes_eval = models.CharField(max_length=32,choices=evaluation, default='Weak')
    has_eval = models.CharField(max_length=32,choices=evaluation, default='Weak')
    hers_eval = models.CharField(max_length=32,choices=evaluation, default='Weak')
    hirs_eval = models.CharField(max_length=32,choices=evaluation, default='Weak')
    efs_eval = models.CharField(max_length=32,choices=evaluation, default='Weak')
    ees_eval = models.CharField(max_length=32,choices=evaluation, default='Weak')
    sers_eval = models.CharField(max_length=32,choices=evaluation, default='Weak')
    sirs_eval = models.CharField(max_length=32,choices=evaluation, default='Weak')

    c_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.c_time)

class JF (models.Model):

    age_group = models.IntegerField(default=0)
    sex = models.CharField(max_length=32,choices=gender, default='male')

    nf_mean = models.IntegerField(default=0)
    ne_mean = models.IntegerField(default=0)
    kf_mean = models.IntegerField(default=0)
    ke_mean = models.IntegerField(default=0)
    apf_mean = models.IntegerField(default=0)
    ad_mean = models.IntegerField(default=0)
    hf_mean = models.IntegerField(default=0)
    her_mean = models.IntegerField(default=0)
    hir_mean = models.IntegerField(default=0)
    ef_mean = models.IntegerField(default=0)
    ee_mean = models.IntegerField(default=0)
    ser_mean = models.IntegerField(default=0)
    sir_mean = models.IntegerField(default=0)

    nf_sd = models.IntegerField(default=0)
    ne_sd = models.IntegerField(default=0)
    kf_sd = models.IntegerField(default=0)
    ke_sd = models.IntegerField(default=0)
    apf_sd = models.IntegerField(default=0)
    ad_sd = models.IntegerField(default=0)
    hf_sd = models.IntegerField(default=0)
    her_sd = models.IntegerField(default=0)
    hir_sd = models.IntegerField(default=0)
    ef_sd = models.IntegerField(default=0)
    ee_sd = models.IntegerField(default=0)
    ser_sd = models.IntegerField(default=0)
    sir_sd = models.IntegerField(default=0)

    def __str__(self):
        return str(self.sex)+' '+str(self.age_group)

class History_JF (models.Model):
    user = models.ForeignKey('User', on_delete=models.CASCADE)

    sex = models.CharField(max_length=32,choices=gender, default='male')
    age = models.IntegerField(default=0)

    nf = models.IntegerField(default=0)
    ne = models.IntegerField(default=0)
    kf = models.IntegerField(default=0)
    ke = models.IntegerField(default=0)
    apf = models.IntegerField(default=0)
    ad = models.IntegerField(default=0)
    hf = models.IntegerField(default=0)
    her = models.IntegerField(default=0)
    hir = models.IntegerField(default=0)
    ef = models.IntegerField(default=0)
    ee = models.IntegerField(default=0)
    ser = models.IntegerField(default=0)
    sir = models.IntegerField(default=0)

    nf_eval = models.CharField(max_length=32,choices=evaluation, default='Weak')
    ne_eval = models.CharField(max_length=32,choices=evaluation, default='Weak')
    kf_eval = models.CharField(max_length=32,choices=evaluation, default='Weak')
    ke_eval = models.CharField(max_length=32,choices=evaluation, default='Weak')
    apf_eval = models.CharField(max_length=32,choices=evaluation, default='Weak')
    ad_eval = models.CharField(max_length=32,choices=evaluation, default='Weak')
    hf_eval = models.CharField(max_length=32,choices=evaluation, default='Weak')
    her_eval = models.CharField(max_length=32,choices=evaluation, default='Weak')
    hir_eval = models.CharField(max_length=32,choices=evaluation, default='Weak')
    ef_eval = models.CharField(max_length=32,choices=evaluation, default='Weak')
    ee_eval = models.CharField(max_length=32,choices=evaluation, default='Weak')
    ser_eval = models.CharField(max_length=32,choices=evaluation, default='Weak')
    sir_eval = models.CharField(max_length=32,choices=evaluation, default='Weak')

    c_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.c_time)

class FP (models.Model):

    age_group = models.IntegerField(default=0)
    sex = models.CharField(max_length=32,choices=gender, default='male')

    fdt_mean = models.IntegerField(default=0)
    hpt9_mean = models.IntegerField(default=0)
    seb_mean = models.IntegerField(default=0)
    lj_mean = models.IntegerField(default=0)
    mwt6_mean = models.IntegerField(default=0)
    vj_mean = models.IntegerField(default=0)
    tst_mean = models.IntegerField(default=0)
    csrt_mean = models.FloatField(default=0)
    sts_mean = models.IntegerField(default=0)
    botb_mean = models.IntegerField(default=0)

    fdt_sd = models.IntegerField(default=0)
    hpt9_sd = models.IntegerField(default=0)
    seb_sd = models.IntegerField(default=0)
    lj_sd = models.IntegerField(default=0)
    mwt6_sd = models.IntegerField(default=0)
    vj_sd = models.IntegerField(default=0)
    tst_sd = models.IntegerField(default=0)
    csrt_sd = models.FloatField(default=0)
    sts_sd = models.IntegerField(default=0)
    botb_sd = models.IntegerField(default=0)

    def __str__(self):
        return str(self.sex)+' '+str(self.age_group)

class History_FP (models.Model):
    user = models.ForeignKey('User', on_delete=models.CASCADE)

    sex = models.CharField(max_length=32,choices=gender, default='male')
    age = models.IntegerField(default=0)

    fdt = models.IntegerField(default=0)
    hpt9 = models.IntegerField(default=0)
    seb = models.IntegerField(default=0)
    lj = models.IntegerField(default=0)
    mwt6 = models.IntegerField(default=0)
    vj = models.IntegerField(default=0)
    tst = models.IntegerField(default=0)
    csrt = models.FloatField(default=0)
    sts = models.IntegerField(default=0)
    botb = models.IntegerField(default=0)

    fdt_eval = models.CharField(max_length=32,choices=evaluation, default='Weak')
    hpt9_eval = models.CharField(max_length=32,choices=evaluation, default='Weak')
    seb_eval = models.CharField(max_length=32,choices=evaluation, default='Weak')
    lj_eval = models.CharField(max_length=32,choices=evaluation, default='Weak')
    mwt6_eval = models.CharField(max_length=32,choices=evaluation, default='Weak')
    vj_eval = models.CharField(max_length=32,choices=evaluation, default='Weak')
    tst_eval = models.CharField(max_length=32,choices=evaluation, default='Weak')
    csrt_eval = models.CharField(max_length=32,choices=evaluation, default='Weak')
    sts_eval = models.CharField(max_length=32,choices=evaluation, default='Weak')
    botb_eval = models.CharField(max_length=32,choices=evaluation, default='Weak')
    
    c_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.c_time)

myproject/project/templates/project/Physical outcome measures.html
<!doctype html>
<!-- Website template by freewebsitetemplates.com -->
<html>
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Physical outcome measures</title>
	{% load static %}
	<link rel="stylesheet" href="{% static 'project/css/style.css' %}" type="text/css">
	<link rel="stylesheet" type="text/css" href="{% static 'project/css/mobile.css' %}">
	<script src="{% static 'project/js/mobile.js' %}" type="text/javascript"></script>
</head>
<body>
    <script>
		document.addEventListener("DOMContentLoaded", function(event) {
			if(sessionStorage.getItem("loginSuccess") == "true"){
				document.getElementById("loginword").style.display = "none";
				document.getElementById("loginlogo").style.display = "block";
			}
	  });
	  
	</script>
	<div id="page">
		<div id="header">
			<div>
				<a href="/index" class="logo"><img src="{% static 'project/images/logo.png' %}" width="340" height="55" alt="Logo"></a>
				<ul id="navigation">
					<li]>
						<a href="/index">Home</a>
					</li>
					<li class="selected">
						<a href="/physical_outcome_measures">Physical outcome measures</a>
					</li>
					<li>
						<a href="/measurement_research">measurement research</a>	
					</li>
					<li>
						<a href="/self-reported_measures">self-reported measures</a>
						
					</li>
					<li>
						<a href="/contact">Contact</a>
					</li>
					<li>
						<a id="loginword" href="/login">Login</a>
					</li>
				</ul>

				<a href="/login" class="login" id="loginlogo" style="display:none"><img src="{% static 'project/images/login.png' %}" width="50" height="50"alt=""></a>
			</div>
		</div>
		<div id="body" class="about">
			<div class="header">
				<div>
					<h1>Do the Culculations</h1>
					<h2>Overview</h2>
					<p>We are currently measuring the physical capabilities of 1000 healthy individuals across the lifespan to help us identify the range of ‘normal’ variation in the healthy population. This information will be used to generate a global database of ‘normal values’. We are also collecting information regarding lifestyle and well-being as well as investigating the ‘gene for speed’ in the healthy population. We hope to better understand the processes of healthy ageing and development, and the link between genetics and physical capability.</p>
					<p>The 1000 Norms Project database will be shared with healthcare professionals around the globe by The University of Sydney via a free, secure online portal. Personal details are not displayed anywhere in the database. This database will be an important tool for the diagnosis and management of disease around the world.</p>
				</div>
			</div>
			<div class="body">
				<div><a href="/ims">
					<img src="{% static 'project/images/iso.jpg' %}" width="500" height="200"alt="Isometric Muscle Strength">
					<h2>Isometric Muscle Strength</h2>
					</a>
				</div>
			</div>
			<div class="footer">
				<div><a href="/jf">
					<img src="{% static 'project/images/jrm.png' %}" width="500" height="200"alt="Joint Range of Motion">
					<h2>Joint Range of Motion</h2>
					</a>
				</div>
			</div>
			<div class="section">
				<div><a href="/fp">
					<img src="{% static 'project/images/f.jpg' %}" width="500" height="200"alt="Joint Range of Motion">
					<h2>Functional Measures</h2>
					</a>
				</div>
			</div>
		</div>
		<div id="footer">
			<div class="connect">
				<div>
					<h1>Find more on</h1>
					<div>
						<a href="https://www.facebook.com/" class="facebook">facebook</a>
						<a href="https://twitter.com/" class="twitter">twitter</a>

					</div>
				</div>
			</div>
			<div class="footnote">
				<div>
					<p>&copy; 2018 BY UNIVERSITY of SYDNEY| ALL RIGHTS RESERVED</p>
				</div>
			</div>
		</div>
	</div>
</body>
</html>

myproject/project/templates/project/ims.html

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>IMS test</title>
</head>
<body>
    <style>
    pre {outline: 1px solid #ccc; padding: 5px; margin: 5px; }
    .string { color: green; }
    .number { color: darkorange; }
    .boolean { color: blue; }
    .null { color: magenta; }
    .key { color: red; }
</style>
     <div style="margin: 15% 40%;">
        <h1>IMS test</h1>

       <form id="ims_form">
        {% if message %}
                    <div class="alert alert-warning">{{ message }}</div>
                {% endif %}
            <p>
                <label for="id_age">Age</label>
                <input type="text" id="id_age" name="age" placeholder="" autofocus required / >
            </p>

            <p>
                <label for="id_gender">Gender</label>
                <select id="id_gender" name="gender"> 
                    <option value="male">male</option> 
                    <option value="female">female</option> 
                </select> 
                
            </p>
          
            <p>
                <label for="id_gs">gs</label>
                <input type="text" id="id_gs" placeholder="" name="gs" required >
            </p>

            <p>
                <label for="id_apfs">apfs</label>
                <input type="text" id="id_apfs" placeholder="" name="apfs" required>
            </p>

            <p>
                <label for="id_ads">ads</label>
                <input type="text" id="id_ads" placeholder="" name="ads" required>
            </p>

            <p>
                <label for="id_kfs">kfs</label>
                <input type="text" id="id_kfs" placeholder="" name="kfs" required>
            </p>

            <p>
                <label for="id_kes">kes</label>
                <input type="text" id="id_kes" placeholder="" name="kes" required>
            </p>

            <p>
                <label for="id_has">has</label>
                <input type="text" id="id_has" placeholder="" name="has" required>
            </p>

            <p>
                <label for="id_hers">hers</label>
                <input type="text" id="id_hers" placeholder="" name="hers" required>
            </p>

            <p>
                <label for="id_hirs">hirs</label>
                <input type="text" id="id_hirs" placeholder="" name="hirs" required>
            </p>

            <p>
                <label for="id_efs">efs</label>
                <input type="text" id="id_efs" placeholder="" name="efs" required>
            </p>

            <p>
                <label for="id_ees">ees</label>
                <input type="text" id="id_ees" placeholder="" name="ees" required>
            </p>

            <p>
                <label for="id_sers">sers</label>
                <input type="text" id="id_sers" placeholder="" name="sers" required>
            </p>

            <p>
                <label for="id_sirs">sirs</label>
                <input type="text" id="id_sirs" placeholder="" name="sirs" required>
            </p>
            
            <input type="button" id="ims_submit" value="Submit IMS">
        </form>
    </div>
    <div>
        <res id='result'>
        </res>
    </div>
 
    <script src="http://apps.bdimg.com/libs/jquery/1.11.1/jquery.min.js"></script>
    <script>
        jQuery(document).ajaxSend(function(event, xhr, settings) {
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie != '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) == (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    function sameOrigin(url) {
        // url could be relative or scheme relative or absolute
        var host = document.location.host; // host + port
        var protocol = document.location.protocol;
        var sr_origin = '//' + host;
        var origin = protocol + sr_origin;
        // Allow absolute or scheme relative URLs to same origin
        return (url == origin || url.slice(0, origin.length + 1) == origin + '/') ||
            (url == sr_origin || url.slice(0, sr_origin.length + 1) == sr_origin + '/') ||
            // or any other URL that isn't scheme relative or absolute i.e relative.
            !(/^(\/\/|http:|https:).*/.test(url));
    }
    function safeMethod(method) {
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
 
    if (!safeMethod(settings.type) && sameOrigin(settings.url)) {
        xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
    }
});
    </script>
    <script>
        function syntaxHighlight(json) {
    if (typeof json != 'string') {
        json = JSON.stringify(json, undefined, 2);
    }
    json = json.replace(/&/g, '&').replace(/</g, '<').replace(/>/g, '>');
    return json.replace(/("(\\u[a-zA-Z0-9]{4}|\\[^u]|[^\\"])*"(\s*:)?|\b(true|false|null)\b|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)/g, function(match) {
        var cls = 'number';
        if (/^"/.test(match)) {
            if (/:$/.test(match)) {
                cls = 'key';
            } else {
                cls = 'string';
            }
        } else if (/true|false/.test(match)) {
            cls = 'boolean';
        } else if (/null/.test(match)) {
            cls = 'null';
        }
        return '<span class="' + cls + '">' + match + '</span>';
    });
}
    </script>
        <script> 
            $.fn.serializeJson=function(){
            var serializeObj={};
            var array=this.serializeArray();
            var str=this.serialize();
            $(array).each(function(){
                if(serializeObj[this.name]){
                    if($.isArray(serializeObj[this.name])){
                        serializeObj[this.name].push(this.value);
                    }else{
                        serializeObj[this.name]=[serializeObj[this.name],this.value];
                    }
                }else{
                    serializeObj[this.name]=this.value;
                }
            });
            return serializeObj;
        };
    $("#ims_submit").click(function() {
        form_str = $("#ims_form").serializeJson();
        console.log('submitted data:');
        console.log(form_str);
        
        $.ajax("/ims/submit",{
                  data:JSON.stringify(form_str),
                   contentType:"application/json",
                   type:"POST",
                   dataType: 'JSON',
                   success:function(data){
                        console.log('responsed data:');
                        console.log(data);
                        $("#result").html(syntaxHighlight(data));
                    }
             
        });
    })
        </script>
</body>
</html>

myproject/project/templates/project/ims_result.html
ims_result

myproject/project/templates/project/jf.html

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>JF test</title>
</head>
<body>
    <style>
    pre {outline: 1px solid #ccc; padding: 5px; margin: 5px; }
    .string { color: green; }
    .number { color: darkorange; }
    .boolean { color: blue; }
    .null { color: magenta; }
    .key { color: red; }
</style>
     <div style="margin: 15% 40%;">
        <h1>JF test</h1>

       <form id="jf_form">
        {% if message %}
                    <div class="alert alert-warning">{{ message }}</div>
                {% endif %}
            <p>
                <label for="id_age">Age</label>
                <input type="text" id="id_age" name="age" placeholder="" autofocus required / >
            </p>

            <p>
                <label for="id_gender">Gender</label>
                <select id="id_gender" name="gender"> 
                    <option value="male">male</option> 
                    <option value="female">female</option> 
                </select> 
                
            </p>
          
            <p>
                <label for="id_kf">kf</label>
                <input type="text" id="id_kf" placeholder="" name="kf" required >
            </p>

            <p>
                <label for="id_ke">ke</label>
                <input type="text" id="id_ke" placeholder="" name="ke" required>
            </p>

            <p>
                <label for="id_apf">apf</label>
                <input type="text" id="id_apf" placeholder="" name="apf" required>
            </p>

            <p>
                <label for="id_ad">ad</label>
                <input type="text" id="id_ad" placeholder="" name="ad" required>
            </p>

            <p>
                <label for="id_hf">hf</label>
                <input type="text" id="id_hf" placeholder="" name="hf" required>
            </p>

            <p>
                <label for="id_her">her</label>
                <input type="text" id="id_her" placeholder="" name="her" required>
            </p>

            <p>
                <label for="id_hir">hir</label>
                <input type="text" id="id_hir" placeholder="" name="hir" required>
            </p>

            <p>
                <label for="id_ef">ef</label>
                <input type="text" id="id_ef" placeholder="" name="ef" required>
            </p>

            <p>
                <label for="id_ee">ee</label>
                <input type="text" id="id_ee" placeholder="" name="ee" required>
            </p>

            <p>
                <label for="id_ser">ser</label>
                <input type="text" id="id_ser" placeholder="" name="ser" required>
            </p>

            <p>
                <label for="id_sir">sir</label>
                <input type="text" id="id_sir" placeholder="" name="sir" required>
            </p>

            <input type="button" id="jf_submit" value="Submit JF">
        </form>
    </div>
    <div>
        <res id='result'>
        </res>
    </div>
 
    <script src="http://apps.bdimg.com/libs/jquery/1.11.1/jquery.min.js"></script>
    <script>
        jQuery(document).ajaxSend(function(event, xhr, settings) {
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie != '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) == (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    function sameOrigin(url) {
        // url could be relative or scheme relative or absolute
        var host = document.location.host; // host + port
        var protocol = document.location.protocol;
        var sr_origin = '//' + host;
        var origin = protocol + sr_origin;
        // Allow absolute or scheme relative URLs to same origin
        return (url == origin || url.slice(0, origin.length + 1) == origin + '/') ||
            (url == sr_origin || url.slice(0, sr_origin.length + 1) == sr_origin + '/') ||
            // or any other URL that isn't scheme relative or absolute i.e relative.
            !(/^(\/\/|http:|https:).*/.test(url));
    }
    function safeMethod(method) {
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
 
    if (!safeMethod(settings.type) && sameOrigin(settings.url)) {
        xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
    }
});
    </script>
    <script>
        function syntaxHighlight(json) {
    if (typeof json != 'string') {
        json = JSON.stringify(json, undefined, 2);
    }
    json = json.replace(/&/g, '&').replace(/</g, '<').replace(/>/g, '>');
    return json.replace(/("(\\u[a-zA-Z0-9]{4}|\\[^u]|[^\\"])*"(\s*:)?|\b(true|false|null)\b|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)/g, function(match) {
        var cls = 'number';
        if (/^"/.test(match)) {
            if (/:$/.test(match)) {
                cls = 'key';
            } else {
                cls = 'string';
            }
        } else if (/true|false/.test(match)) {
            cls = 'boolean';
        } else if (/null/.test(match)) {
            cls = 'null';
        }
        return '<span class="' + cls + '">' + match + '</span>';
    });
}
    </script>
        <script> 
            $.fn.serializeJson=function(){
            var serializeObj={};
            var array=this.serializeArray();
            var str=this.serialize();
            $(array).each(function(){
                if(serializeObj[this.name]){
                    if($.isArray(serializeObj[this.name])){
                        serializeObj[this.name].push(this.value);
                    }else{
                        serializeObj[this.name]=[serializeObj[this.name],this.value];
                    }
                }else{
                    serializeObj[this.name]=this.value;
                }
            });
            return serializeObj;
        };
    $("#jf_submit").click(function() {
        form_str = $("#jf_form").serializeJson();
        console.log('submitted data:');
        console.log(form_str);
        
        $.ajax("/jf/submit",{
                  data:JSON.stringify(form_str),
                   contentType:"application/json",
                   type:"POST",
                   dataType: 'JSON',
                   success:function(data){
                        console.log('responsed data:');
                        console.log(data);
                        $("#result").html(syntaxHighlight(data));
                    }
             
        });
    })
        </script>
</body>
</html>